package com.myservice.Vo;

import lombok.Data;

@Data
public class FileInfoVo {
    /**
     * Id
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private Integer id;

    /**
     * 文件名
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String fileName;

    /**
     * 文件类型
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_url
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.status
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_md5
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String fileMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.create_time
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.del_time
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String delTime;

    @Override
    public String toString() {
        return "FileInfoVo{" +
                "id=" + id +
                ", fileName='" + fileName + '\'' +
                ", fileType='" + fileType + '\'' +
                ", fileUrl='" + fileUrl + '\'' +
                ", status='" + status + '\'' +
                ", fileMd5='" + fileMd5 + '\'' +
                ", createTime='" + createTime + '\'' +
                ", delTime='" + delTime + '\'' +
                '}';
    }
}
