package com.myservice.bean;

import java.util.Date;

public class UploadFilesInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.id
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_name
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_size
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private Integer fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_type
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_url
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.status
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_md5
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private String fileMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.create_time
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.del_time
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private Date delTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.fast_group
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private String fastGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.fast_path
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    private String fastPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.id
     *
     * @return the value of tbl_upload_files_info.id
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.id
     *
     * @param id the value for tbl_upload_files_info.id
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.file_name
     *
     * @return the value of tbl_upload_files_info.file_name
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.file_name
     *
     * @param fileName the value for tbl_upload_files_info.file_name
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.file_size
     *
     * @return the value of tbl_upload_files_info.file_size
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.file_size
     *
     * @param fileSize the value for tbl_upload_files_info.file_size
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.file_type
     *
     * @return the value of tbl_upload_files_info.file_type
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.file_type
     *
     * @param fileType the value for tbl_upload_files_info.file_type
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.file_url
     *
     * @return the value of tbl_upload_files_info.file_url
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.file_url
     *
     * @param fileUrl the value for tbl_upload_files_info.file_url
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.status
     *
     * @return the value of tbl_upload_files_info.status
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.status
     *
     * @param status the value for tbl_upload_files_info.status
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.file_md5
     *
     * @return the value of tbl_upload_files_info.file_md5
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.file_md5
     *
     * @param fileMd5 the value for tbl_upload_files_info.file_md5
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5 == null ? null : fileMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.create_time
     *
     * @return the value of tbl_upload_files_info.create_time
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.create_time
     *
     * @param createTime the value for tbl_upload_files_info.create_time
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.del_time
     *
     * @return the value of tbl_upload_files_info.del_time
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.del_time
     *
     * @param delTime the value for tbl_upload_files_info.del_time
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.fast_group
     *
     * @return the value of tbl_upload_files_info.fast_group
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public String getFastGroup() {
        return fastGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.fast_group
     *
     * @param fastGroup the value for tbl_upload_files_info.fast_group
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setFastGroup(String fastGroup) {
        this.fastGroup = fastGroup == null ? null : fastGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.fast_path
     *
     * @return the value of tbl_upload_files_info.fast_path
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public String getFastPath() {
        return fastPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.fast_path
     *
     * @param fastPath the value for tbl_upload_files_info.fast_path
     *
     * @mbg.generated Mon Jun 10 00:16:43 CST 2019
     */
    public void setFastPath(String fastPath) {
        this.fastPath = fastPath == null ? null : fastPath.trim();
    }
}