package com.myservice.bean;

import java.util.Date;

public class UploadFilesInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.id
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_name
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_type
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_url
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.status
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.file_md5
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private String fileMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.create_time
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_upload_files_info.del_time
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    private Date delTime;

    public UploadFilesInfo() {
    }

    public UploadFilesInfo(Integer id, String fileName, String fileType, String fileUrl, String status, String fileMd5, Date createTime, Date delTime) {
        this.id = id;
        this.fileName = fileName;
        this.fileType = fileType;
        this.fileUrl = fileUrl;
        this.status = status;
        this.fileMd5 = fileMd5;
        this.createTime = createTime;
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.id
     *
     * @return the value of tbl_upload_files_info.id
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.id
     *
     * @param id the value for tbl_upload_files_info.id
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.file_name
     *
     * @return the value of tbl_upload_files_info.file_name
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.file_name
     *
     * @param fileName the value for tbl_upload_files_info.file_name
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.file_type
     *
     * @return the value of tbl_upload_files_info.file_type
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.file_type
     *
     * @param fileType the value for tbl_upload_files_info.file_type
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.file_url
     *
     * @return the value of tbl_upload_files_info.file_url
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.file_url
     *
     * @param fileUrl the value for tbl_upload_files_info.file_url
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.status
     *
     * @return the value of tbl_upload_files_info.status
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.status
     *
     * @param status the value for tbl_upload_files_info.status
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.file_md5
     *
     * @return the value of tbl_upload_files_info.file_md5
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.file_md5
     *
     * @param fileMd5 the value for tbl_upload_files_info.file_md5
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5 == null ? null : fileMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.create_time
     *
     * @return the value of tbl_upload_files_info.create_time
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.create_time
     *
     * @param createTime the value for tbl_upload_files_info.create_time
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_upload_files_info.del_time
     *
     * @return the value of tbl_upload_files_info.del_time
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_upload_files_info.del_time
     *
     * @param delTime the value for tbl_upload_files_info.del_time
     *
     * @mbg.generated Thu May 30 09:25:13 CST 2019
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    @Override
    public String toString() {
        return "UploadFilesInfo{" +
                "id=" + id +
                ", fileName='" + fileName + '\'' +
                ", fileType='" + fileType + '\'' +
                ", fileUrl='" + fileUrl + '\'' +
                ", status='" + status + '\'' +
                ", fileMd5='" + fileMd5 + '\'' +
                ", createTime=" + createTime +
                ", delTime=" + delTime +
                '}';
    }
}